apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherforecastapi
  labels:
    app: weather-forecast
spec:
  replicas: 1
  selector:
    matchLabels:
      service: weatherforecastapi
  template:
    metadata:
      labels:
        app: weather-forecast
        service: weatherforecastapi
    spec:
      containers:
        - name: weatherforecast
          image: edwinatdev/weatherforecast:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: webapi-service
  labels:
    app: weather-forecast
    service: weatherforecastapi
spec:
  type: NodePort
  ports:
    - port: 80
      # targetPort: 80
      protocol: TCP
      nodePort: 30007
  selector:
    service: weatherforecastapi