apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherforecastapi
  labels:
    app: weather-forecast
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-forecast
  template:
    metadata:
      labels:
        app: weather-forecast
    spec:
      containers:
        - name: weatherforecast
          image: edwinatdev/weatherforecast:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://*:5000
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
          resources:
            limits:
              cpu: "0.4"
              memory: "125Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: webapi-service
spec:
  type: LoadBalancer
  ports:
    - port: 30007
      targetPort: 5000
  selector:
    app: weather-forecast